### ISSUE TITLE
New developer

### ISSUE THREAD

**Issue by Nothing-personal** [andriynikolaenko1012/comivo#1]
Hello! I am a new developer of this project. Could you please help me understand your source code. I should connect API to this app. 
Where should I start?

**Comment by andriynikolaenko1012** [comment]
Hello. You need to start from beginning)

2016-09-27 21:29 GMT+03:00 Kevin Khanda <notifications@github.com>:

**Comment by Nothing-personal** [comment]
Sorry, what do you mean?
Rewriting the application?

**Comment by andriynikolaenko1012** [comment]
between us - I do not advise to work with this client, he pays nothing

2016-09-27 22:35 GMT+03:00 Андрей Николаенко <
andriy.nikolaenko1012@gmail.com>:

**Comment by Nothing-personal** [comment]
Oh, I see. Thanks for your advise

**Comment by andriynikolaenko1012** [comment]
Why do you think I'm not doing anything right now? He did not pay me 3 weeks

2016-09-27 22:35 GMT+03:00 Андрей Николаенко <
andriy.nikolaenko1012@gmail.com>:

**Comment by Nothing-personal** [comment]
Hmm.. Okay, thank you once more for your advice.

**Comment by andriynikolaenko1012** [comment]
you try, maybe you'll have better luck than me))

2016-09-27 22:38 GMT+03:00 Kevin Khanda <notifications@github.com>:

**Comment by Nothing-personal** [comment]
Я так понимаю, Вы русский?

**Comment by andriynikolaenko1012** [comment]
да, а что?


2016-09-27 22:42 GMT+03:00 Kevin Khanda <notifications@github.com>:

**Comment by andriynikolaenko1012** [comment]
добався в скайп, тут влом общатся prime10121990

2016-09-27 22:45 GMT+03:00 Андрей Николаенко <
andriy.nikolaenko1012@gmail.com>:

**Comment by andriynikolaenko1012** [comment]
привет. ты работаешь?

27 сентября 2016 г., 22:47 пользователь Андрей Николаенко <
andriy.nikolaenko1012@gmail.com> написал:
